---
  apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    name: "[DEPLOYMENT_NAME]"
    annotations:
      kubernetes.io/change-cause: "[ROLLOUT_NOTE]"
    namespace: "[NAMESPACE]"
  spec:
    progressDeadlineSeconds: 120
    replicas: 1
    template:
      metadata:
        labels:
          name: "[DEPLOYMENT_LABEL]"
      spec:
        containers:
          - image: "[DOCKER_IMAGE]"
            name: "[DEPLOYMENT_NAME]"
            env:
              -
                name: "NODE_ENV"
                value: "[NODE_ENV]"
              -
                name: "BUST"
                value: "[BUST]"
            resources:
              requests:
                cpu: [REQUEST_CPU]
            ports:
              - containerPort: 3000
        nodeSelector:
          [NODE_SELECTOR]

